abbr -a -- gd 'git diff'
abbr -a -- gl 'git pull'
abbr -a -- gloga 'git log --oneline --decorate --graph --all'
abbr -a -- de 'docker container exec -it'
abbr -a -- dcd 'docker-compose down'
abbr -a -- gstp 'git stash pop'
abbr -a -- glog 'git log --oneline --decorate --graph'
abbr -a -- dcu 'docker-compose up -d'
abbr -a -- t 'npm test'
abbr -a -- d docker
abbr -a -- gco 'git checkout'
abbr -a -- o xdg-open
abbr -a -- - 'cd -'
abbr -a -- dce 'docker-compose exec'
abbr -a -- ga 'git add'
abbr -a -- gc 'git commit'
abbr -a -- gsta 'git stash'
abbr -a -- grb 'git rebase'
abbr -a -- dr 'docker container run'
abbr -a -- g git
abbr -a -- gm 'git merge'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- db 'docker image build -t'
abbr -a -- gb 'git branch'
abbr -a -- dp 'docker system prune -af --volumes'
abbr -a -- dc docker-compose
abbr -a -- dcr 'docker-compose down && docker-compose up -d'
abbr -a -- cb 'xclip -i -selection clipboard'
abbr -a -- dcb 'docker-compose build --parallel'
abbr -a -- gf 'git fetch -pP'
abbr -a -- dcl 'docker-compose logs -f'
abbr -a -- gcb 'git checkout -b'
abbr -a -- gst 'git status'
abbr -a -- gp 'git push'
abbr -a -- k 'ssh prod-k9s'
abbr -a -- wga 'sudo wg-quick up atlas'
abbr -a -- wgd 'sudo wg-quick down atlas'
