Section "Device"
    Identifier "intel"
    Driver "modesetting"
    BusID "PCI:0:2:0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "intel"
    SubSection "Display"
        Virtual 7680 4320
    EndSubSection
EndSection
