#!/bin/bash
# Ult's Manjaro GNOME 17 setup.

set -euxo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if [[ "$(id -u)" -eq 0 ]]; then
  echo 'This script cannot be run as root.'
  exit 1
fi

# Set up Network Manager.
sudo ln -f network-manager/99-disable-wifi-powersave.conf /etc/NetworkManager/conf.d/99-disable-wifi-powersave.conf
sudo ln -f network-manager/99-prevent-dns-changes.conf /etc/NetworkManager/conf.d/99-prevent-dns-changes.conf

# Set up AdGuard DNS.
echo $'\nname_servers="176.103.130.130 176.103.130.131"' | sudo tee -a /etc/resolvconf.conf
sudo resolvconf -u

# Set up Pacman hooks.
./vivaldi/install-customizations
sudo ln -f shutter/shutter.hook /usr/share/libalpm/hooks/shutter.hook
sudo ln -f blueman/blueman.hook /usr/share/libalpm/hooks/blueman.hook

sudo sed -i'' '/# Misc options/a ILoveCandy' /etc/pacman.conf
cat pacman/repos.conf | sudo tee -a /etc/pacman.conf
sudo pacman -Syu
sudo pacman -Rs --noconfirm tlp manjaro-gnome-maia-theme manjaro-gnome-assets nautilus-empty-file bijiben gnome-screenshot empathy telepathy-accounts-signon ms-office-online libreoffice-fresh brasero gthumb totem grilo-plugins firefox
sudo pacman -S --needed --noconfirm base-devel yaourt yarn python-pip git fish docker mongodb chrome-gnome-shell xorg-xprop xclip shotwell vlc papirus-icon-theme noto-fonts-emoji vivaldi-snapshot vivaldi-snapshot-ffmpeg-codecs google-chrome slack-desktop
yaourt -S --needed --noconfirm visual-studio-code-bin shadowsocks-qt5 shutter stacer nvm terraform skypeforlinux-stable-bin ttf-fira-code
pip install --user --upgrade awscli
curl -sSL https://www.astrill.com/downloads/astrill-setup-linux64.sh > astrill-setup-linux64.sh
chmod +x astrill-setup-linux64.sh
sudo ./astrill-setup-linux64.sh --sudo
rm astrill-setup-linux64.sh

# Set up fonts.
sudo ln -f fonts/local.conf /etc/fonts/local.conf

# Set up $PATH.
echo PATH="$(yarn global bin):~/.local/bin:\$PATH" >> ~/.bash_profile
fish --command 'set -U fish_user_paths (yarn global bin) ~/.local/bin $fish_user_paths'

# Set up Docker.
sudo gpasswd -a "$(whoami)" docker

# Set up fish, nvm, fast-nvm-fish.
chsh -s /usr/bin/fish
mkdir -p ~/.config/fish/functions
ln -f fish/functions/fish_prompt.fish ~/.config/fish/functions/fish_prompt.fish
./fish/theme.fish
./fish/abbr.fish
sudo chown -R "$(whoami)" /usr/share/nvm
echo 'source /usr/share/nvm/init-nvm.sh' >> ~/.bashrc
echo 'set -gx NVM_DIR /usr/share/nvm' >> ~/.config/fish/config.fish
curl -sSL https://raw.githubusercontent.com/brigand/fast-nvm-fish/master/nvm.fish > ~/.config/fish/functions/nvm.fish
fish --command 'nvm install 10'
echo 'nvm use 10' >> ~/.config/fish/config.fish

# Set up GNOME.
timedatectl set-ntp 1
gsettings set org.gnome.desktop.datetime automatic-timezone true
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
gsettings set org.gnome.desktop.privacy remember-recent-files false
gsettings set org.gnome.desktop.privacy recent-files-max-age 0
gsettings set org.gnome.desktop.session idle-delay 900
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.background picture-uri "file://$(pwd)/images/wallpaper.jpg"
gsettings set org.gnome.desktop.screensaver picture-uri "file://$(pwd)/images/wallpaper.jpg"
gsettings set org.gnome.system.proxy mode 'manual'
gsettings set org.gnome.system.proxy.socks host '127.0.0.1'
gsettings set org.gnome.system.proxy.socks port 1080
gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '10.0.0.0/8', '192.168.0.0/16', '172.16.0.0/12']"
gsettings set org.gtk.Settings.FileChooser sort-directories-first true
gsettings set org.gtk.Settings.FileChooser show-hidden true

# Replace gnome-screenshot keybindings with shutter.
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot ''
gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot-clip ''
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot ''
gsettings set org.gnome.settings-daemon.plugins.media-keys window-screenshot-clip ''
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot ''
gsettings set org.gnome.settings-daemon.plugins.media-keys area-screenshot-clip ''
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Shutter - capture desktop"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "shutter --full --profile=silent --no_session --exit_after_capture"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "Print"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name "Shutter - capture window"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command "shutter --window --profile=silent --no_session --exit_after_capture"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding "<Ctrl>Print"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name "Shutter - capture selection"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command "shutter --select --profile=silent --no_session --exit_after_capture"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding "<Shift>Print"
mkdir -p ~/.shutter/profiles
ln -f shutter/profiles/silent.xml ~/.shutter/profiles/silent.xml
ln -f shutter/profiles/silent_accounts.xml ~/.shutter/profiles/silent_accounts.xml

# Don't suspend when lid is closed.
sudo sed -i'' -E 's/.*(HandleLidSwitch=).*/\1ignore/' /etc/systemd/logind.conf

# Set up system.
echo 'fs.inotify.max_user_watches=524288' | sudo tee /etc/sysctl.d/40-max-user-watches.conf
sudo sysctl --system

# Set up startup applications and services.
sudo systemctl mask --now man-db.timer

# Clean up.
rm -f ~/Readme ~/Templates/*

cat << EOF
✨ Setup finished successfully.

#
# Manual config
#

Dash to dock:
- Intelligent autohide: animation duration .15s, hide timeout 0s
- Icon size limit: 48

Hide Top Bar:
- Animation: overview .3s, edge: .1s

VS Code Sync Settings: https://gist.github.com/UltCombo/6107218148de04eb7b2165b5a4c00645
DuckDuckGo config: https://duckduckgo.com/?q=%s&t=vivaldi&kae=d&k1=-1&kaj=m&kam=osm&kak=-1&kax=-1&kaq=-1&kap=-1&kao=-1&k5=2&k7=282c34&kj=21252b&k9=98c379&kx=61afef
Shadowsocks config
EOF
