#!/usr/bin/fish

# Git.
abbr gst 'git status'
abbr gd 'git diff'
abbr ga 'git add'
abbr gc 'git commit'
abbr gb 'git branch'
abbr gco 'git checkout'
abbr gcb 'git checkout -b'
abbr gf 'git fetch -pP'
abbr gl 'git pull'
abbr gp 'git push'
abbr gm 'git merge'
abbr grb 'git rebase'
abbr gcp 'git cherry-pick'
abbr gsta 'git stash'
abbr gstp 'git stash pop'
abbr glog 'git log --oneline --decorate --graph'
abbr gloga 'git log --oneline --decorate --graph --all'
abbr g 'git'

# Docker.
abbr db 'docker image build -t'
abbr dr 'docker container run'
abbr de 'docker container exec -it'
abbr dp 'docker system prune -af --volumes'
abbr d 'docker'
abbr dcb 'docker-compose build --parallel'
abbr dcd 'docker-compose down'
abbr dcu 'docker-compose up -d'
abbr dcr 'docker-compose down && docker-compose up -d'
abbr dce 'docker-compose exec'
abbr dcl 'docker-compose logs -f'
abbr dc 'docker-compose'

# Utilities.
abbr o 'xdg-open'
abbr t 'npm test'
abbr cb 'xclip -i -selection clipboard'
abbr - 'cd -'
