#!/bin/bash

set -euxo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

VIVALDI_CUSTOMIZATIONS_DIR='/usr/lib/vivaldi-customizations/'

sudo mkdir -p "$VIVALDI_CUSTOMIZATIONS_DIR"
sudo ln -f lib/* "$VIVALDI_CUSTOMIZATIONS_DIR"
sudo ln -f bin/* /usr/bin/
